# Default values for ITL Keycloak Tenants
# This is a YAML-formatted file.

# ModSecurity Configuration
modsecurity:
  enabled: true

# Keycloak Configuration
keycloak:
  enabled: true
  
  # Init containers for custom setup (optional)
  initContainers:
    - name: theme-downloader
      image: busybox:1.37.0
      command:
        - sh
        - -c
      args:
        - |
          echo "Downloading Keycloak theme..."
          wget https://github.com/MinBZK/keycloak-theme/releases/download/v1.0.1/keycloak-nl-design-system.jar -O /opt/keycloak/providers/keycloak-nl-design-system.jar
          echo "Theme downloaded successfully"
      volumeMounts:
        - name: keycloak-providers
          mountPath: /opt/keycloak/providers/
      securityContext:
        runAsUser: 0
      resources:
        requests:
          memory: 64Mi
          cpu: 50m
        limits:
          memory: 128Mi
          cpu: 100m
  
  # Additional volumes for init containers (optional)
  additionalVolumes:
    - name: keycloak-providers
      emptyDir: {}
  
  # Additional volume mounts for main container (optional)
  additionalVolumeMounts:
    - name: keycloak-providers
      mountPath: /opt/keycloak/providers/
      readOnly: false

# Database Configuration  
database:
  enabled: true
  instances: 3
  name: keycloak
  username: keycloak
  
  # Storage configuration
  storage:
    size: 20Gi
    storageClass: ha-gen-lh
    
  # Resource limits
  resources:
    requests:
      memory: 512Mi
      cpu: 200m
    limits:
      memory: 2Gi
      cpu: 1000m
      
  # Monitoring
  monitoring:
    enabled: true
    
  # Backup configuration (optional)
  backup:
    enabled: false
    destinationPath: "s3://backup-bucket/postgresql"
    walRetention: "7d"
    dataRetention: "30d"
    jobs: 1
    s3Credentials:
      secretName: s3-credentials
      
  # Connection pooling (optional)
  connectionPooler:
    enabled: false
    instances: 3
    type: rw
    poolMode: transaction
