apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Name }}-{{ .Values.keycloak.name }}-tls
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
spec:
  secretName: {{ .Release.Name }}-{{ .Values.keycloak.name }}-tls
  issuerRef:
    name: letsencrypt-issuer
    kind: ClusterIssuer
  dnsNames:
    - {{ .Values.keycloak.hostname.hostname }}
{{- range .Values.certificate.additionalDnsNames }}
    - {{ . }}
{{- end }}