apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: {{ .Release.Name }}-{{ .Values.keycloak.name }}
spec:
  instances: {{ .Values.keycloak.instances }}
  db:
    vendor: {{ .Values.keycloak.db.vendor }}
    host: {{ .Values.keycloak.db.host }}
    usernameSecret:
      name: {{ .Release.Name }}-{{ .Values.keycloak.name }}-credentials
      key: username
    passwordSecret:
      name: {{ .Release.Name }}-{{ .Values.keycloak.name }}-credentials
      key: password
  http:
    httpEnabled: true
    httpPort: 8180
    httpsPort: 8543
    tlsSecret: {{ .Release.Name }}-{{ .Values.keycloak.name }}-tls
  hostname:
    hostname: {{ .Values.keycloak.hostname.hostname }}
    strict: false
  proxy:
    headers: {{ .Values.keycloak.proxy.headers }}
  networkPolicy:
    enabled: false
  ingress:
      enabled: true
      className: traefik