apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
    name: {{ .Release.Name }}-{{ .Values.keycloak.name }}
spec:
    instances: 3
    imageName: ghcr.io/cloudnative-pg/postgresql:16
    storage:
        size: 10Gi
        storageClass: ha-dbs-lh
    bootstrap:
        initdb:
            database: {{ .Release.Name }}-{{ .Values.keycloak.name }}
            owner: {{ .Release.Name }}-{{ .Values.keycloak.name }}
            secret:
                name: {{ .Release.Name }}-{{ .Values.keycloak.name }}-db-secret
    monitoring:
        enablePodMonitor: true
    resources:
        requests:
            cpu: 250m
            memory: 512Mi
        limits:
            cpu: 500m
            memory: 1Gi
    superuserSecret:
        name: {{ .Release.Name }}-{{ .Values.keycloak.name }}-db-superuser-secret
    serviceAccountTemplate:
        metadata:
            name: {{ .Release.Name }}-{{ .Values.keycloak.name }}-pg-sa