{{- if .Values.database.useCNPG }}
---
# Database owner user secret for CNPG
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "itl.keycloack.tenants.databaseName" . }}-db-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "itl.keycloack.tenants.labels" . | nindent 4 }}
type: kubernetes.io/basic-auth
data:
  username: {{ printf "%s-db" (include "itl.keycloack.tenants.databaseName" .) | b64enc }}
  password: {{ .Values.database.cnpg.userPassword | default (randAlphaNum 32) | b64enc }}

---
# Superuser secret for CNPG
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "itl.keycloack.tenants.databaseName" . }}-db-superuser-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "itl.keycloack.tenants.labels" . | nindent 4 }}
type: kubernetes.io/basic-auth
data:
  username: {{ "postgres" | b64enc }}
  password: {{ .Values.database.cnpg.superuserPassword | default (randAlphaNum 32) | b64enc }}

---
# Application secret for Keycloak to connect to the database
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-db-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "itl.keycloack.tenants.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ printf "%s-db" (include "itl.keycloack.tenants.databaseName" .) | b64enc }}
  password: {{ .Values.database.cnpg.userPassword | default (randAlphaNum 32) | b64enc }}
{{- end }}